In [38]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [39]:
import numpy as np
print(np.__version__)

1.26.4


In [40]:
import numpy as np

# 1D
a1 = np.array([1, 2, 3, 4, 5])

# 2D
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# 3D (например, 2 «слоя» 2×2)
a3 = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]]], dtype='float32')

print(a2.shape)  # (2, 3) — 2 строки, 3 столбца
print(a2.size)   # 6       — всего элементов
print(a2.dtype)  # тип (например, int64)i

# Лайфхак: укажи тип сразу — np.array([1, 2, 3], dtype='float32') — и сэкономишь память/время.

print(a3.shape)
print(a3.size)
print(a3.dtype)

(2, 3)
6
int64
(2, 2, 2)
8
float32


In [41]:
x = np.array([1, 2, 3, 4], dtype=float)
print(x * 10)        # [10. 20. 30. 40.]
print((x - x.mean()) / x.std())  # стандартизация без циклов

[10. 20. 30. 40.]
[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [42]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A[1, 2])   # 6  (2-я строка, 3-й столбец)
print(A[1, :])   # [4 5 6] — вся 2-я строка
print(A[:, 0])   # [1 4 7] — весь 1-й столбец

6
[4 5 6]
[1 4 7]


In [43]:
b = np.arange(10)      # [0 1 2 3 4 5 6 7 8 9]
print(b[2:7])          # [2 3 4 5 6]
print(b[::2])          # [0 2 4 6 8]
print(A[0:2, 1:3])     # [[2 3],
                       #  [5 6]]

[2 3 4 5 6]
[0 2 4 6 8]
[[2 3]
 [5 6]]


In [44]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])     # [30 40 50] — фильтр по условию

rows = [0, 2]
cols = [1, 2]
print(A[rows, cols])     # [2 9] — выборка по спискам индексов

[30 40 50]
[2 9]


In [45]:
# Срез — это view (представление), изменения затрагивают исходный массив.

x = np.arange(5)
y = x[1:4]     # view
y[0] = 100
print(x)       # [  0 100   2   3   4]

# Нужна копия? Делай .copy()
z = x[1:4].copy()

[  0 100   2   3   4]


In [46]:
# Генерация чисел и перемешивание
print(np.random.randint(10, 50, 6))  # 6 целых в [10, 50)
print(np.random.rand(2, 3))       # 2×3 из [0,1)
print(np.random.randn(3))           # 3 из N(0,1)

x = np.arange(1, 8)
np.random.permutation(x)      # перемешанная копия x


# Быстрый диапазон:

np.arange(10)      # 0..9
np.linspace(0, 1, 5)  # 5 точек от 0 до 1 включительно | array([0.  , 0.25, 0.5 , 0.75, 1.  ])


[10 31 48 47 14 27]
[[0.00144024 0.85614469 0.90894276]
 [0.18869125 0.57050708 0.31592056]]
[ 1.27374067 -0.92668659 -1.13383775]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
# Изменение массива через индексацию
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10                    # точечная замена
arr[1:4] = [20, 30, 40]        # замена среза
arr[arr > 10] = 100            # условная замена
arr[[1, 3]] = 500              # fancy-индексация
print(arr)

[  1 500 100 500   5]


In [48]:
# Арифметика и broadcasting

# Broadcasting — правило, по которому NumPy «растягивает» меньшие массивы до формы большего для поэлементных операций.

# Примеры
a = np.array([1, 2, 3])
print(f'a:\n{a + 5}')                 # [6 7 8]     — скаляр на вектор

B = np.array([[0, 1, 2],
              [3, 4, 5]])
print(f'b:\n{B + a}')                 # прибавит [1,2,3] к каждой строке

c = np.array([[1],
              [2],
              [3]])
d = np.array([1, 2, 3])
print(f'c + d:\n{c + d}')                 # «крест-складка» → 3×3 матрица

a:
[6 7 8]
b:
[[1 3 5]
 [4 6 8]]
c + d:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [49]:
# Частые задачи с broadcasting

# Нормализация по строкам/столбцам:

X = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])

col_sum = X.sum(axis=0, keepdims=True)   # (1,3)
X_col_norm = X / col_sum                  # деление каждого столбца на его сумму

row_sum = X.sum(axis=1, keepdims=True)   # (3,1)
X_row_norm = X / row_sum


# Внешнее произведение (outer product):

u = np.array([1, 2, 3]).reshape(-1, 1)  # (3,1)
v = np.array([1, 2, 3])                 # (3,)
M = u * v                               # (3,3)


In [50]:
# Агрегации: sum, mean, min, max (и оси)

# По умолчанию — по всем элементам; axis ограничивает направление:

A = np.array([[1, 2, 3],
              [4, 5, 6]])

np.sum(A)            # 21 — все элементы
np.sum(A, axis=0)    # [5 7 9]   — по столбцам
np.sum(A, axis=1)    # [6 15]    — по строкам

np.mean(A, axis=0)   # среднее по столбцам
np.min(A), np.max(A)

(1, 6)

In [51]:
# Важная статистика: mean, median, std (и распределения)
x = np.array([1, 2, 2, 3, 100])
print(np.mean(x))     # среднее
print(np.median(x))   # медиана (устойчива к выбросам)
print(np.std(x))      # стандартное отклонение


# Для нормального распределения mean ≈ median, «большая часть» точек в пределах ±1σ.

# Для скошенного (asymmetric) распределения медиана надёжнее среднего как «центра».

21.6
2.0
39.205101708833766


In [52]:
# Работа с пропусками (NaN) и масками
y = np.array([1., 2., np.nan, 4.])
np.isnan(y)                 # [False False  True False]
np.nanmean(y)               # среднее, игнорируя NaN


# Masked arrays позволяют «скрыть» значения и считать поверх видимых:

m = np.ma.masked_invalid(y)
m.mean()                    # игнорирует замаскированные элементы

2.3333333333333335

In [53]:
# Преобразования данных: reshape и transpose
# Reshape (переформование)

# Меняем форму без копирования данных (если возможно):

data = np.arange(1, 7)      # [1 2 3 4 5 6]
print(data.reshape(2, 3))
print(data.reshape(3, 2))
# Универсально:
print(data.reshape(-1, 3))  # «подбери нужное число строк»


# Ошибка будет, если итоговое число элементов не совпадает.

# Transpose (перестановка осей)

M = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(M.T)     # [[1,3,5],
               #  [2,4,6]]


# Комбинируй reshape и .T для подготовки данных к моделям/визуализациям, матричным операциям.

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [ ]:
# Базовые операции с изображениями (пример со средним по каналу)

# Идея: RGB-картинка — это массив H×W×3. Если посчитать среднее по оси цветов — получим градации серого.

from PIL import Image
import numpy as np

img = Image.open('soldier.png')
arr = np.array(img)               # (H, W, 3)
gray = arr.mean(axis=2).round().astype(np.uint8)
Image.fromarray(gray).save('out.jpg')


# Важно привести тип к uint8, иначе сохранение может дать неожиданные цвета.


Оптимизация производительности

Векторизация вместо циклов — главный источник ускорения.

Выбирай подходящий dtype (например, float32 вместо float64, если точности хватает).

Избегай лишних копий: предпочитай срезы/view, используй out= в некоторых функциях.

Проверяй формы перед broadcasting — так меньше неожиданных аллокаций и ошибок.